# tasks when remote ansible-role-dbmanage
---
- debug: msg="This is just a place holder in case we want to do things in remote mode"

- debug: var="{{ database_admin_user }}"
- debug: var="{{ database_admin_password }}"
- debug: var="{{ database_hostname }}"
- debug: var="{{ app_db_credentials }}"
